In [1]:
import numpy as np

In [8]:
uTP=1.0    # utility True Positives 
uFP=0.0    # utility False Positives
uFN=-5.0    # utility False Negatives
uTN=1.0   # utility True Negatives
utMat = np.array([[uTP,uFP],[uFN,uTN]]) # Classifier utility matrix

In [9]:
utMat

array([[ 1.,  0.],
       [-5.,  1.]])

In [13]:
b = np.array([[0.25,0.75]])

In [14]:
b

array([[0.25, 0.75]])

In [16]:
c = np.dot(utMat,b.transpose())

In [17]:
c

array([[ 0.25],
       [-0.5 ]])

In [18]:
f = np.sum(c)

In [19]:
f

-0.25

In [20]:
c

array([[ 0.25],
       [-0.5 ]])

In [21]:
p = np.array([[0.25,0.75],[0.25,0.75],[0.25,0.75]])
p

array([[0.25, 0.75],
       [0.25, 0.75],
       [0.25, 0.75]])

In [22]:
np.sum(p)

3.0

In [23]:
np.max(-1873.67399947549, -4.33791129399509E-09)

TypeError: 'float' object cannot be interpreted as an integer

In [24]:
-4.33791129399509E-09

-4.33791129399509e-09

In [25]:
a = -4.33791129399509E-09

In [26]:
a

-4.33791129399509e-09

In [27]:
b = -1873.67399947549

In [28]:
b

-1873.67399947549

In [31]:
min(a,b)

-1873.67399947549